[[redirects]]
  from = "/"
  to = "/generate"
  status = 301

[[redirects]]
  from = "/home"
  to = "/generate"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
